# version: '3.9'

services:
  database:
    image: postgres:alpine
    container_name: postgres-db
    hostname: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=queso
      - POSTGRES_DB=ex00

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database

volumes:
  postgres_data: